### ISSUE TITLE
Install failing on Devise 3.2.0

### ISSUE THREAD

**Issue by pdrlps** [n8/devise_marketable#1]
Looks very interesting, but I got a small problem testing it...

```
Bundler could not find compatible versions for gem "devise":
  In Gemfile:
    devise_marketable (>= 0) ruby depends on
      devise (~> 2.2.7) ruby

    devise (3.2.0)
```

Keep up the great work!

**Comment by n8** [comment]
Can you try the 0.0.4 version of the gem please. 

```
gem 'devise_marketable', "~> 0.0.4"
```

It removes the dependency on the devise version.

**Comment by pdrlps** [comment]
Working! Thanks, I'll let you how it goes...
